# Set ip forwarding on in /proc and do not reload the sysctl file
- sysctl: name="net.ipv4.ip_forward" value=1 sysctl_set=yes

- name: insert iptables template
  template: src=iptables.j2 dest=/etc/network/if-pre-up.d/iptables mode=0751
  #notify: restart iptables

- name: insert iptables template
  template: src=iptables.up.rules.j2 dest=/etc/iptables.up.rules mode=0644
  notify: restart iptables